# Generated by Django 3.2.4 on 2021-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(max_length=10)),
                ('protein', models.FloatField(max_length=4)),
                ('carbohydrates', models.FloatField(max_length=4)),
                ('fats', models.FloatField(max_length=4)),
            ],
        ),
    ]
