# Generated by Django 3.2.4 on 2021-07-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210713_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(max_length=10)),
                ('protein', models.FloatField(max_length=4)),
                ('carbohydrates', models.FloatField(max_length=4)),
                ('fats', models.FloatField(max_length=4)),
                ('macros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.macros')),
            ],
        ),
    ]
