# Generated by Django 3.2.4 on 2021-07-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='macros',
        ),
        migrations.AddField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
