# Generated by Django 3.2.4 on 2021-07-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210714_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macros',
            name='user',
        ),
        migrations.AddField(
            model_name='macros',
            name='goals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.goals'),
            preserve_default=False,
        ),
    ]
