# Generated by Django 3.2.4 on 2021-07-15 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20210715_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macros',
            name='goals',
        ),
        migrations.AddField(
            model_name='macros',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
